#!/bin/bash
# Fetch (or verify) the pinned upstream checkout for agentic-image.
# Upstream code is NEVER committed: it lives in oss/ (gitignored) and is
# fetched at runtime by this script.
#
# Usage:
#   bash scripts/fetch_upstream.sh [--update]
#
# Stdout is one JSON document — fetch_upstream/v1:
#   {"schema": "fetch_upstream/v1",
#    "repos": [{"name": "ideogram4", "url": "...", "commit": "sha"|null,
#               "action": "cloned|verified|updated|present-no-git|clone-failed",
#               "digests": {"rel/path": "sha256", ...},
#               "missing_required_files": []}],
#    "docs_written": "docs/upstream.md", "ok": true}
set -euo pipefail

UPDATE=0
if [[ "${1:-}" == "--update" ]]; then UPDATE=1; fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OSS="$REPO_ROOT/oss"
mkdir -p "$OSS"

URL="https://github.com/ideogram-oss/ideogram4.git"
REF="main"
NAME="ideogram4"
DEST="$OSS/$NAME"

# Files the studio actually consumes (existence is the gate; digests pin them).
REQUIRED=(
  "run_inference.py"
  "pyproject.toml"
  "LICENSE.md"
  "docs/prompting.md"
  "docs/inference.md"
  "src/ideogram4/sampler_configs.py"
  "src/ideogram4/caption_verifier.py"
)

ACTION=""; COMMIT=""
if [[ ! -d "$DEST/.git" ]]; then
  if [[ -d "$DEST" ]]; then
    ACTION="present-no-git"
  elif command -v git >/dev/null 2>&1 \
    && git clone --depth 1 --branch "$REF" "$URL" "$DEST" >/dev/null 2>&1; then
    ACTION="cloned"
  else
    ACTION="clone-failed"
  fi
else
  if [[ "$UPDATE" == "1" ]]; then
    (cd "$DEST" && git fetch origin "$REF" >/dev/null 2>&1 \
      && git reset --hard "origin/$REF" >/dev/null 2>&1) \
      && ACTION="updated" || ACTION="verified"
  else
    ACTION="verified"
  fi
  COMMIT="$(cd "$DEST" && git rev-parse HEAD 2>/dev/null || true)"
fi

MISSING=()
DIGESTS="{"
FIRST=1
for rel in "${REQUIRED[@]}"; do
  if [[ -f "$DEST/$rel" ]]; then
    sha="$(sha256sum "$DEST/$rel" | cut -d' ' -f1)"
    [[ $FIRST == 0 ]] && DIGESTS+=","
    DIGESTS+="\"$rel\":\"$sha\""
    FIRST=0
  else
    MISSING+=("$rel")
  fi
done
DIGESTS+="}"

OK=true
[[ "$ACTION" == "clone-failed" ]] && OK=false
[[ ${#MISSING[@]} -gt 0 ]] && OK=false

MISSING_JSON="[]"
if [[ ${#MISSING[@]} -gt 0 ]]; then
  MISSING_JSON="[\"$(IFS='","'; echo "${MISSING[*]}")\"]"
fi

# Regenerate docs/upstream.md every run (records the pin this machine runs).
cat > "$REPO_ROOT/docs/upstream.md" <<EOF
# Upstream pins (generated by scripts/fetch_upstream.sh — do not hand-edit)

| Checkout | URL | Ref | Commit |
|---|---|---|---|
| oss/ideogram4 | $URL | $REF | ${COMMIT:-not fetched} |

Required files digested this run: ${#REQUIRED[@]} checked, ${#MISSING[@]} missing.
Re-run \`bash scripts/fetch_upstream.sh\` after pulling to refresh this file.
EOF

printf '{"schema":"fetch_upstream/v1","repos":[{"name":"%s","url":"%s","commit":%s,"action":"%s","digests":%s,"missing_required_files":%s}],"docs_written":"docs/upstream.md","ok":%s}\n' \
  "$NAME" "$URL" \
  "$([[ -n "$COMMIT" ]] && echo "\"$COMMIT\"" || echo null)" \
  "$ACTION" "$DIGESTS" "$MISSING_JSON" "$OK"
